<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="libbot_description">

    <!-- Adding friction -->
    <gazebo reference="base_link">
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
    </gazebo>

    <gazebo reference="back_left_wheel_link">
        <mu1>0.8</mu1>
        <mu2>0.8</mu2>
    </gazebo>

    <gazebo reference="back_right_wheel_link">
        <mu1>0.8</mu1>
        <mu2>0.8</mu2>
    </gazebo>

    <gazebo reference="caster_link">
        <mu1>0.1</mu1>
        <mu2>0.1</mu2>
    </gazebo>

    <!-- Plugins -->
    <gazebo>

        <!-- Joint state publisher -->
        <plugin filename="gz-sim-joint-state-publisher-system"
            name="gz::sim::systems::JointStatePublisher">

            <topic>joint_states</topic>

            <joint_name>left_wheel_joint</joint_name>
            <joint_name>right_wheel_joint</joint_name>

            <joint_name>door_joint</joint_name>

        </plugin>

        <!-- Differential drive -->
        <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
            <right_joint>right_wheel_joint</right_joint>
            <left_joint>left_wheel_joint</left_joint>

            <wheel_separation>${chassis_breadth+wheel_length}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>

            <max_linear_accleration>1</max_linear_accleration>

            <topic>cmd_vel_out</topic>
            <tf_topic>robot/tf</tf_topic>
            <odom_topic>robot/odom</odom_topic>
            
            <frame_id>odom</frame_id>
            <child_frame_id>base_footprint</child_frame_id>
            <odom_publisher_frequency>50</odom_publisher_frequency>

        </plugin>

        <!-- Door joint controller -->
        <plugin
            filename="gz-sim-joint-position-controller-system"
            name="gz::sim::systems::JointPositionController">
            <joint_name>door_joint</joint_name>
            <topic>door_control</topic>
            <p_gain>1</p_gain>
            <i_gain>0.1</i_gain>
            <d_gain>0.01</d_gain>
            <i_max>1</i_max>
            <i_min>-1</i_min>
            <cmd_max>1000</cmd_max>
            <cmd_min>-1000</cmd_min>
        </plugin>

    </gazebo>

</robot>